In [2]:
import pandas as pd
df = pd.read_excel(r"C:\Users\hp\Downloads\ola_project.xlsx")
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,NaN
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,NaN

In [3]:
num_cols = ['C_TAT','V_TAT', 'Driver_Ratings', 'Customer_Rating']

for col in num_cols:
    df[col] = df.groupby('Vehicle_Type')[col] \
                .transform(lambda x: x.fillna(x.median()))

In [4]:
df['Canceled_Rides_by_Customer'] = df['Canceled_Rides_by_Customer'].fillna('No')

df['Canceled_Rides_by_Driver'] = df['Canceled_Rides_by_Driver'].fillna('No')

df['Incomplete_Rides'] = df['Incomplete_Rides'].fillna('No')

df['Incomplete_Rides_Reason'] = df['Incomplete_Rides_Reason'].fillna('Not Applicable')

df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,168.0,85.0,No,Personal & Car related issue,No,Not Applicable,444,NaN,0,4.0,4.0,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,No,No,No,Not Applicable,158,Cash,13,4.1,4.0,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,No,No,No,Not Applicable,386,UPI,40,4.2,4.8,NaN
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,168.0,85.0,Driver is not moving towards pickup location,No,No,Not Applicable,384,NaN,0,4.0,4.0,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,No,No,No,Not Applicable,822,Credit Card,45,4.0,3.0,NaN

In [5]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.head()

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,v_tat,c_tat,canceled_rides_by_customer,canceled_rides_by_driver,incomplete_rides,incomplete_rides_reason,booking_value,payment_method,ride_distance,driver_ratings,customer_rating,vehicle_images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,168.0,85.0,No,Personal & Car related issue,No,Not Applicable,444,NaN,0,4.0,4.0,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,No,No,No,Not Applicable,158,Cash,13,4.1,4.0,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,No,No,No,Not Applicable,386,UPI,40,4.2,4.8,NaN
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,168.0,85.0,Driver is not moving towards pickup location,No,No,Not Applicable,384,NaN,0,4.0,4.0,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,No,No,No,Not Applicable,822,Credit Card,45,4.0,3.0,NaN

In [6]:
df=df.drop("vehicle_images", axis =1)
df.head()

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,v_tat,c_tat,canceled_rides_by_customer,canceled_rides_by_driver,incomplete_rides,incomplete_rides_reason,booking_value,payment_method,ride_distance,driver_ratings,customer_rating
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,168.0,85.0,No,Personal & Car related issue,No,Not Applicable,444,NaN,0,4.0,4.0
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,No,No,No,Not Applicable,158,Cash,13,4.1,4.0
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,No,No,No,Not Applicable,386,UPI,40,4.2,4.8
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,168.0,85.0,Driver is not moving towards pickup location,No,No,Not Applicable,384,NaN,0,4.0,4.0
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,No,No,No,Not Applicable,822,Credit Card,45,4.0,3.0

In [7]:
bins = [0, 5, 15, 30, 50]

labels = ['Short', 'Medium', 'Long', 'Very Long']

df['distance_type'] = pd.cut(
    df['ride_distance'],
    bins=bins,
    labels=labels
)
df.head()

,date,time,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,v_tat,c_tat,canceled_rides_by_customer,canceled_rides_by_driver,incomplete_rides,incomplete_rides_reason,booking_value,payment_method,ride_distance,driver_ratings,customer_rating,distance_type
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,168.0,85.0,No,Personal & Car related issue,No,Not Applicable,444,NaN,0,4.0,4.0,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,No,No,No,Not Applicable,158,Cash,13,4.1,4.0,Medium
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,No,No,No,Not Applicable,386,UPI,40,4.2,4.8,Very Long
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,168.0,85.0,Driver is not moving towards pickup location,No,No,Not Applicable,384,NaN,0,4.0,4.0,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,No,No,No,Not Applicable,822,Credit Card,45,4.0,3.0,Very Long

In [8]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\hp\anaconda3\anaconda\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\anaconda\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\hp\anaconda3\anaconda\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\anaconda\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
from sqlalchemy import create_engine
username = "postgres"
password = "1234"
host = "localhost"
port = "5432"
database = "Ola_Database"
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name = "OLA_last"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'OLA_last' in database 'Ola_Database'.